### ISSUE TITLE
A4.4.e - Contributions of each author.

### ISSUE THREAD

**Issue by Albertoperleo** [gii-is-psg2/psg2-2223-g4-44#106]
Include details on concrete tasks performed by each member of the group. We suggest using a matrix or table to sum up this information.

**Comment by alecorralg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/106?planning-poker) with Zenhub @Albertoperleo @Gabrielvcg @ignaciowarleta
