### ISSUE TITLE
A3.4-a Análisis del Código Fuente y Métricas Asociadas 

### ISSUE THREAD

**Issue by ignaciowarleta** [gii-is-psg2/psg2-2223-g4-44#40]

**Comment by alecorralg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/40?planning-poker) with Zenhub @Albertoperleo @Gabrielvcg @ignaciowarleta
