### ISSUE TITLE
A3.3-a Metricas de proceso agil y recursos para el sprint 2

### ISSUE THREAD

**Issue by ignaciowarleta** [gii-is-psg2/psg2-2223-g4-44#44]

**Comment by Gabrielvcg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/44?planning-poker) with Zenhub @Albertoperleo

**Comment by Gabrielvcg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/44?planning-poker) with Zenhub @ignaciowarleta

**Comment by Gabrielvcg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/44?planning-poker) with Zenhub @alecorralg
