### ISSUE TITLE
A3.2-a Crear funcionalidad "Causes"

### ISSUE THREAD

**Issue by ignaciowarleta** [gii-is-psg2/psg2-2223-g4-44#46]
Crear Funcionalidad Causas con:

1. Nombre de la causa
2. Presupuesto total conseguido (suma donaciones)
3. Presupuesto a alcanzar
4. Botón de creación de donation
5. Boton de navegacion para los detalles del la causa

Detalles de la Causa:
Nombre y descripcion(string)
Presupuesto objetivo(numeric),
active non-profit organization (string) 

Los clientes pueden donar una cantidad especifica hasta que se alcance la suma total del presupuesto objetivo y se cierra la causa

Sección de Causas

**Comment by Albertoperleo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/46?planning-poker) with Zenhub @alecorralg @Gabrielvcg @ignaciowarleta
