### ISSUE TITLE
A3.2-c Crear funcionalidad "Adoptions"

### ISSUE THREAD

**Issue by ignaciowarleta** [gii-is-psg2/psg2-2223-g4-44#48]
Añadir funcionalidad Adoptar 
EL dueño puede crear una solicitud de adopcion 
Otros dueños pueden listar las mascotas disponibles para adoptar y aplicar la adopcion(Descripcion de la metodologia del cuidado de la mascota)
El dueño que acepta la solicitud, transfiere la mascota al nuevo dueño

**Comment by Albertoperleo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/48?planning-poker) with Zenhub @alecorralg @Gabrielvcg @ignaciowarleta
