### ISSUE TITLE
A3.2 Desplegar aplicación

### ISSUE THREAD

**Issue by ignaciowarleta** [gii-is-psg2/psg2-2223-g4-44#49]

**Comment by Albertoperleo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/49?planning-poker) with Zenhub @alecorralg

**Comment by Albertoperleo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/49?planning-poker) with Zenhub @Gabrielvcg @ignaciowarleta
