### ISSUE TITLE
Generar un release en GitHub con notas previo a coding A3.2

### ISSUE THREAD

**Issue by Albertoperleo** [gii-is-psg2/psg2-2223-g4-44#57]

**Comment by alecorralg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/57?planning-poker) with Zenhub @Albertoperleo @ignaciowarleta @Gabrielvcg

**Comment by Albertoperleo** [comment]
Ya se ha creado la release, cuando revisen los compañeros y el tutor la subida a AppEngine, se podrá cerrar esta issue.

**Comment by Albertoperleo** [comment]
Creada la tag y la release.
