### ISSUE TITLE
Añadir funcionalidad de poner en adopción

### ISSUE THREAD

**Issue by alecorralg** [gii-is-psg2/psg2-2223-g4-44#61]
1. Modificar PetService
2. Añadir vista para cambiar parametros de adopción

**Comment by Albertoperleo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/61?planning-poker) with Zenhub @alecorralg @Gabrielvcg @ignaciowarleta
