### ISSUE TITLE
Validaciones de concurrencia en las reservas

### ISSUE THREAD

**Issue by Albertoperleo** [gii-is-psg2/psg2-2223-g4-44#71]

**Comment by Albertoperleo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PSG2-G4-44-64085ee6569648002bb147a9/issues/gii-is-psg2/psg2-2223-g4-44/71?planning-poker) with Zenhub @alecorralg @Gabrielvcg @ignaciowarleta

**Comment by Gabrielvcg** [comment]
Ciertamente, parece que algunos nos equivocamos en la estimación del planning póker de esta tarea, merece más dificultad, al igual que Nachete que subestimo esta empresa.
